SKPOnline/Controllers/CustomerController.cs
namespace SKPOnline.Controllers
{
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using Database;
    using Microsoft.AspNet.Identity;
    using Models;
    using Models.ViewModels;

    [Authorize(Roles = RolesEn.Customer)]
    public class CustomerController : Controller
    {
        public ActionResult Index(string message)
        {
            ViewBag.StatusMessage = message;

            CustomerProfileVM model;

            using (var dbContext = ApplicationDbContext.Create())
            {
                var userId = User.Identity.GetUserId();
                var profile = dbContext.Customers.FirstOrDefault(customer => customer.Id == userId);
                model = new CustomerProfileVM
                        {
                            NickName = profile?.NickName,
                            Gender = profile?.Gender,
                            FirstName = profile?.FirstName,
                            Surname = profile?.Surname,
                            BirthDate = profile?.BirthDate,
                            PhoneNumber = profile?.PhoneNumber,
                            Voivodeship = profile?.Voivodeship,
                            City = profile?.City,
                            Street = profile?.Street,
                            HouseNumber = profile?.HouseNumber,
                            ApartmentNumber = profile?.ApartmentNumber,
                            Avatar = profile?.Avatar
                        };
            }

            return View(model);
        }

        public ActionResult Edit()
        {
            CustomerProfileVM model;

            using (var dbContext = ApplicationDbContext.Create())
            {
                var userId = User.Identity.GetUserId();
                var profile = dbContext.Customers.FirstOrDefault(customer => customer.Id == userId);
                model = new CustomerProfileVM
                        {
                            NickName = profile?.NickName,
                            Gender = profile?.Gender,
                            FirstName = profile?.FirstName,
                            Surname = profile?.Surname,
                            BirthDate = profile?.BirthDate,
                            PhoneNumber = profile?.PhoneNumber,
                            Voivodeship = profile?.Voivodeship,
                            City = profile?.City,
                            Street = profile?.Street,
                            HouseNumber = profile?.HouseNumber,
                            ApartmentNumber = profile?.ApartmentNumber,
                            Avatar = profile?.Avatar
                        };
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CustomerProfileVM model, HttpPostedFileBase image = null)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var userId = User.Identity.GetUserId();

            if (!EntityManager.IsNickNameUnique(userId, model.NickName))
            {
                ModelState.AddModelError(nameof(model.NickName), "Taka nazwa użytkownika już istnieje.");
                return View(model);
            }

            if (image != null)
            {
                var fileStream = image.InputStream;
                var binaryReader = new BinaryReader(fileStream);
                model.Avatar = binaryReader.ReadBytes((int) fileStream.Length);
            }

            EntityManager.UpdateCustomerProfile(userId, model);

            return RedirectToAction("Index", new {message = "Poprawnie zaktualizowano profil!"});
        }

        public ActionResult Stations(string message)
        {
            ViewBag.StatusMessage = message;

            List<StationVM> model;

            using (var dbContext = ApplicationDbContext.Create())
            {
                var userId = User.Identity.GetUserId();
                var user = dbContext.Customers.FirstOrDefault(customer => customer.Id == userId);

                if (user == null)
                {
                    dbContext.Dispose();
                    return RedirectToAction("Index", new {message = "Wystąpił błąd podczas pobierania listy ulubionych SKP!"});
                }

                model = user.FavouriteStations
                            .Select(station => new StationVM
                                               {
                                                   IdentificationCode = station.IdentificationCode,
                                                   Voivodeship = station.Voivodeship,
                                                   City = station.City
                                               })
                            .OrderBy(station => station.IdentificationCode)
                            .ToList();
            }

            return View(model);
        }
    }
}

SKPOnline/Controllers/StationController.cs
namespace SKPOnline.Controllers
{
    using System;
    using System.Web.Mvc;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.IO;
    using System.Linq;
    using System.Web;
    using Database;
    using Database.Models;
    using Microsoft.AspNet.Identity;
    using Models;
    using Models.ViewModels;

    public class StationController : Controller
    {
        public ActionResult Index(string message)
        {
            ViewBag.StatusMessage = message;

            List<StationVM> model;

            using (var dbContext = ApplicationDbContext.Create())
            {
                model = dbContext.Stations
                                 .Select(station => new StationVM
                                                    {
                                                        IdentificationCode = station.IdentificationCode,
                                                        Voivodeship = station.Voivodeship,
                                                        City = station.City
                                                    })
                                 .OrderBy(station => station.Voivodeship)
                                 .ToList();
            }

            return View(model);
        }

        public ActionResult Details(string message, string identificationCode)
        {
            ViewBag.StatusMessage = message;

            StationDetailsVM model;

            using (var dbContext = ApplicationDbContext.Create())
            {
                var chosenStation = dbContext.Stations.FirstOrDefault(station => station.IdentificationCode == identificationCode);

                if (chosenStation == null)
                {
                    return RedirectToAction("Index", new {message = "Wystąpił błąd podczas wyświetlania strony wybranej SKP."});
                }

                model = new StationDetailsVM
                        {
                            Name = chosenStation.Name,
                            IdentificationCode = chosenStation.IdentificationCode,
                            Voivodeship = chosenStation.Voivodeship,
                            City = chosenStation.City,
                            Street = chosenStation.Street,
                            HouseNumber = chosenStation.HouseNumber,
                            ApartmentNumber = chosenStation.ApartmentNumber,
                            Photo = chosenStation.Photo,
                            Diagnosticians = chosenStation.Diagnosticians,
                            Owner = chosenStation.Owner
                        };
            }

            return View(model);
        }

        [Authorize(Roles = RolesEn.Admin)]
        public ActionResult Delete(string identificationCode)
        {
            using (var dbContext = ApplicationDbContext.Create())
            {
                var stationToDelete = dbContext.Stations.FirstOrDefault(station => station.IdentificationCode == identificationCode);

                if (stationToDelete == null)
                {
                    dbContext.Dispose();
                    return RedirectToAction("Index", new {message = "Wystąpił błąd podczas usuwania SKP."});
                }

                dbContext.Stations.Remove(stationToDelete);
                dbContext.SaveChanges();
            }

            return RedirectToAction("Index", new {message = "Poprawnie usunięto SKP."});
        }

        [Authorize(Roles = RolesEn.Admin + "," + RolesEn.Owner)]
        public ActionResult Edit(string identificationCode)
        {
            EditStationDetailsVM model;

            using (var dbContext = ApplicationDbContext.Create())
            {
                var stationToEdit = dbContext.Stations.FirstOrDefault(station => station.IdentificationCode == identificationCode);

                if (stationToEdit == null)
                {
                    dbContext.Dispose();
                    return RedirectToAction("Index", new {message = "Wystąpił błąd podczas uzyskiwania SKP do edycji."});
                }

                model = new EditStationDetailsVM
                        {
                            Id = stationToEdit.Id,
                            Name = stationToEdit.Name,
                            IdentificationCode = stationToEdit.IdentificationCode,
                            Voivodeship = stationToEdit.Voivodeship,
                            City = stationToEdit.City,
                            Street = stationToEdit.Street,
                            HouseNumber = stationToEdit.HouseNumber,
                            ApartmentNumber = stationToEdit.ApartmentNumber,
                            Photo = stationToEdit.Photo
                        };
            }

            return View(model);
        }

        [Authorize(Roles = RolesEn.Admin + "," + RolesEn.Owner)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditStationDetailsVM model, HttpPostedFileBase image = null)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (!EntityManager.IsIdentificationCodeUnique(model.Id, model.IdentificationCode))
            {
                ModelState.AddModelError(nameof(model.IdentificationCode), "Taki kod rozpoznawczy SKP już istnieje.");
                return View(model);
            }

            if (image != null)
            {
                var fileStream = image.InputStream;
                var binaryReader = new BinaryReader(fileStream);
                model.Photo = binaryReader.ReadBytes((int) fileStream.Length);
            }

            EntityManager.UpdateStationDetails(model);

            return RedirectToAction("Details", new {message = "Poprawnie zaktualizowano dane o SKP!", identificationCode = model.IdentificationCode});
        }

        [Authorize(Roles = RolesEn.Admin)]
        [HttpGet]
        public ActionResult Create(Guid requestId = new Guid(), string requestType = "")
        {
            StationDetailsVM model;

            if (requestId != Guid.Empty && !string.IsNullOrEmpty(requestType))
            {
                using (var dbContext = ApplicationDbContext.Create())
                {
                    switch (requestType)
                    {
                        case "stationRequest":
                        {
                            var stationRequest = dbContext.StationRequests.FirstOrDefault(request => request.Id == requestId);
                            model = new StationDetailsVM
                                    {
                                        Name = stationRequest?.Name,
                                        IdentificationCode = stationRequest?.IdentificationCode,
                                        Voivodeship = stationRequest?.Voivodeship,
                                        City = stationRequest?.City,
                                        Street = stationRequest?.Street,
                                        HouseNumber = stationRequest?.HouseNumber ?? 0,
                                        ApartmentNumber = stationRequest?.ApartmentNumber,
                                        Photo = stationRequest?.Photo
                                    };

                            dbContext.Dispose();
                            return View(model);
                        }
                        case "ownerStationRequest":
                        {
                            var ownerStationRequest = dbContext.OwnerStationRequests.Include(request => request.Owner).FirstOrDefault(request => request.Id == requestId);
                            model = new StationDetailsVM
                                    {
                                        Name = ownerStationRequest?.Name,
                                        IdentificationCode = ownerStationRequest?.IdentificationCode,
                                        Voivodeship = ownerStationRequest?.Voivodeship,
                                        City = ownerStationRequest?.City,
                                        Street = ownerStationRequest?.Street,
                                        HouseNumber = ownerStationRequest?.HouseNumber ?? 0,
                                        ApartmentNumber = ownerStationRequest?.ApartmentNumber,
                                        Photo = ownerStationRequest?.Photo
                                    };

                            dbContext.Dispose();
                            return View(model);
                        }
                    }
                }
            }

            model = new StationDetailsVM();

            return View(model);
        }

        [Authorize(Roles = RolesEn.Admin)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(StationDetailsVM model, HttpPostedFileBase image = null)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (!EntityManager.IsIdentificationCodeUnique(model.IdentificationCode))
            {
                ModelState.AddModelError(nameof(model.IdentificationCode), "Taki kod rozpoznawczy SKP już istnieje.");
                return View(model);
            }

            if (image != null)
            {
                var fileStream = image.InputStream;
                var binaryReader = new BinaryReader(fileStream);
                model.Photo = binaryReader.ReadBytes((int) fileStream.Length);
            }

            var station = EntityManager.CreateStation(model.Name, model.IdentificationCode, model.Voivodeship, model.City, model.Street, model.HouseNumber, model.ApartmentNumber, model.Photo);

            using (var dbContext = ApplicationDbContext.Create())
            {
                dbContext.Stations.Add(station);
                dbContext.SaveChanges();
            }

SKPOnline/Views/Customer/Edit.cshtml
@using SKPOnline.Models
@model SKPOnline.Models.ViewModels.CustomerProfileVM

@section AddToHead
{
    <script type="text/javascript">
        $(function () {
            $('#avatar').change(function () {
                let fileElement = this;
                let fileExtension = "";
                if (fileElement.value.lastIndexOf(".") > 0) {
                    fileExtension = fileElement.value.substring(fileElement.value.lastIndexOf(".") + 1, fileElement.value.length);
                    $('#alert').html(null);
                }
                if (fileExtension.toLowerCase() !== "gif" && fileExtension.toLowerCase() !== "png" && fileExtension.toLowerCase() !== "jpg" && fileExtension.toLowerCase() !== "jpeg") {
                    $('#alert').html("Plik musi być w formacie JPG/PNG/GIF!");
                    fileElement.value = null;
                }
                let fileSize = this.files[0].size/1024/1024;
                if (fileSize > 10) {
                    $('#alert').html("Plik nie może być większy niż 10MB");
                    fileElement.value = null;
                }
            });
        });
</script>
}

@{
    var imageSource = "";

    if (Model.Avatar != null)
    {
        var avatarPath = Convert.ToBase64String(Model.Avatar);
        imageSource = $"data:image/png;base64,{avatarPath}";
    }
}

<h2>Edycja profilu</h2>

@using (Html.BeginForm("Edit", "Customer", FormMethod.Post, new {enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Zmień swoje dane</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.NickName, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.NickName, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.NickName, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.Gender, new SelectList(GenderPl.GetAllGenders()), "Wybierz płeć", new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.Gender, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.FirstName, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Surname, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.BirthDate, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Voivodeship, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.Voivodeship, new SelectList(VoivodeshipsPl.GetAllVoivodeships()), "Wybierz województwo", new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.Voivodeship, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.City, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Street, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HouseNumber, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.HouseNumber, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.HouseNumber, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApartmentNumber, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApartmentNumber, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.ApartmentNumber, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Avatar, htmlAttributes: new {@class = "control-label col-md-2"})
            @Html.HiddenFor(model => model.Avatar)
            <div class="col-md-10">
                <img class="img-thumbnail" src="@imageSource" width="200" height="200" alt="avatar"/>
                <input type="file" name="image" id="avatar" accept="image/png, image/jpeg, image/gif">
                <span class='label label-danger' id="alert"></span>
                @Html.ValidationMessageFor(model => model.Avatar, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do profilu", "Index")
</div>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

SKPOnline/Views/Customer/Index.cshtml
@model SKPOnline.Models.ViewModels.CustomerProfileVM

@{
    var imageSource = "";

    if (Model.Avatar != null)
    {
        var avatarPath = Convert.ToBase64String(Model.Avatar);
        imageSource = $"data:image/png;base64,{avatarPath}";
    }
}

<h2>Profil</h2>

<p class="text-success">@ViewBag.StatusMessage</p>
<div>
    <h4>Twoje dane</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NickName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NickName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Voivodeship)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Voivodeship)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HouseNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HouseNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApartmentNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApartmentNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Avatar)
        </dt>

        <dd>
            <img class="img-thumbnail" src="@imageSource" style="width:200px;height:200px;" alt="avatar"/>
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edytuj profil", "Edit") |
    @Html.ActionLink("Powrót do strony głównej", "Index", "Home")
</p>

SKPOnline/Views/Customer/Stations.cshtml
@model IEnumerable<SKPOnline.Models.ViewModels.StationVM>

<h2>Lista ulubionych stacji kontroli pojazdów</h2>

<p class="text-info">@ViewBag.StatusMessage</p>

@if (Model.Any())
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdentificationCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Voivodeship)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                Dostępne funkcje
            </th>
        </tr>

        @foreach (var station in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => station.IdentificationCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => station.Voivodeship)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => station.City)
                </td>
                <td>
                    <a class="btn btn-info" href="@Url.Action("Details", "Station", new {identificationCode = station.IdentificationCode})">Szczegóły</a>
                    <a class="btn btn-danger" href="@Url.Action("RemoveFromFavourites", "Station", new {identificationCode = station.IdentificationCode})">Usuń z ulubionych</a>
                </td>
            </tr>
        }

    </table>
}
else
{
    <h5>Lista Twoich ulubionych stacji kontroli pojazdów jest pusta. Przejdź do listy SKP, aby jakąś dodać!</h5>
    <a class="btn btn-success" href="@Url.Action("Index", "Station")">Lista SKP</a>
}